apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-chm-status
data:
{{- range $key, $value := .Values.config }}
{{- if not (kindIs "map" $value) }}
{{ $key | indent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}
