apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chm-status-secret-provider
  namespace: default
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.secrets.KEY_VAULT_NAME }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.SECRET_PROVIDER_CLIENT_ID }}
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-DATABASE
          objectType: secret
        - |
          objectName: DB-USERNAME
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: REDIS-HOST
          objectType: secret
        - |
          objectName: REDIS-PASSWORD
          objectType: secret
    tenantId: {{ .Values.secrets.TENANT_ID }}
  secretObjects:
    - secretName: chm-status-secret
      type: Opaque
      data:
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-DATABASE
          key: DB_DATABASE
        - objectName: DB-USERNAME
          key: DB_USERNAME
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: REDIS-HOST
          key: REDIS_HOST
        - objectName: REDIS-PASSWORD
          key: REDIS_PASSWORD
