replicaCount: 1

image:
  repository: dawidholka/chm-status
  pullPolicy: Always
  tag: "1.0.0"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

config:
  APP_NAME: 'CHM Status'
  APP_ENV: 'local'
  APP_KEY: 'base64:ToXKAwrnA/5i1WH+X4rduR9RNrmpe/tvC+ZjxjTLJCo='
  APP_DEBUG: 'true'
